-- 1. Tests for pre-generated relation files

-- create table <name> (c1 int, c2 text)
--   with (appendonly=true, compresstype=zstd)
\! pg_filedump -z -M -k -T zstd test/ao.zstd.gp7

-- create table <name> (c1 int, c2 text)
--   with (appendonly=true, orientation=column, compresstype=zstd)
\! pg_filedump -z -M -k -O column -T zstd test/co.zstd.gp7

-- 2. Tests for new relations files generated by the running GPDB server

create table ao_zstd(c1 int, c2 text) with (appendonly=true, compresstype=zstd) distributed replicated;
create table co_zstd(c1 int, c2 text) with (appendonly=true, orientation=column, compresstype=zstd) distributed replicated;
insert into ao_zstd select i,'abc' from generate_series(1,10)i;
insert into co_zstd select i,'abc' from generate_series(1,10)i;
\set relname ao_zstd
\set ext '.1'
\setenv opt '-z -M -k -T zstd'
\ir run_test.sql
\set relname co_zstd
\set ext '.1'
\setenv opt '-z -M -k -O column -T zstd'
\ir run_test.sql

